### ISSUE TITLE
test function return true when use not url text ("dhttp://~~~")

### ISSUE THREAD

**Issue by morugu** [kevva/url-regex#50] opened 2018-02-22 07:35 UTC
```
const urlRegex = require('url-regex');

urlRegex({exact: true}).test('dhttps://github.com/kevva/url-regex');
//=> true
```

I imagine that return `false`, but return `true`. is it correct?
"dhttps" is not URL.

url-regex: 4.1.1
node: 6.13.0

**Comment by KiranShakya** [comment] 2019-11-19 13:49
Duplicate of #48

**Closed** 2022-01-11 12:19 UTC
